# ESTE ARQUIVO TEM COMO FINALIDADE GUARDAR AS CONSTANTES UTILIZADAS PELOS SCRIPTS R.

cargos <- c('DEPUTADO FEDERAL')
###### VOTAÇÕES NOMINAIS POR MUNICIPIO E ZONA ###### 
# Nomes das colunas da tabela dos candidatos com munzonas

# Até o ano de 2012
col_names_candidatos_munzona_ate_2012 <- tolower(c("DATA_GERACAO", 
                                                   "HORA_GERACAO",
                                                   "ANO_ELEICAO", 
                                                   "NUM_TURNO",
                                                   "DESCRICAO_ELEICAO", 
                                                   "SIGLA_UF", 
                                                   "SIGLA_UE", 
                                                   "CODIGO_MUNICIPIO",
                                                   "NOME_MUNICIPIO", 
                                                   "NUMERO_ZONA", 
                                                   "CODIGO_CARGO", 
                                                   "NUMERO_CAND",
                                                   "SQ_CANDIDATO", 
                                                   "NOME_CANDIDATO", 
                                                   "NOME_URNA_CANDIDATO", 
                                                   "DESCRICAO_CARGO",
                                                   "COD_SIT_CAND_SUPERIOR", 
                                                   "DESC_SIT_CAND_SUPERIOR", 
                                                   "CODIGO_SIT_CANDIDATO", 
                                                   "DESC_SIT_CANDIDATO",
                                                   "CODIGO_SIT_CAND_TOT", 
                                                   "DESC_SIT_CAND_TOT", 
                                                   "NUMERO_PARTIDO", 
                                                   "SIGLA_PARTIDO",
                                                   "NOME_PARTIDO", 
                                                   "SEQUENCIAL_LEGENDA", 
                                                   "NOME_COLIGACAO", 
                                                   "COMPOSICAO_LEGENDA",
                                                   "TOT_VOTOS"))

# A partir do ano de 2014
col_names_candidatos_munzona_2014_em_diante <- tolower(c("DATA_GERACAO", 
                                                         "HORA_GERACAO",
                                                         "ANO_ELEICAO", 
                                                         "NUM_TURNO",
                                                         "DESCRICAO_ELEICAO", 
                                                         "SIGLA_UF", 
                                                         "SIGLA_UE", 
                                                         "CODIGO_MUNICIPIO",
                                                         "NOME_MUNICIPIO", 
                                                         "NUMERO_ZONA", 
                                                         "CODIGO_CARGO", 
                                                         "NUMERO_CAND",
                                                         "SQ_CANDIDATO", 
                                                         "NOME_CANDIDATO", 
                                                         "NOME_URNA_CANDIDATO", 
                                                         "DESCRICAO_CARGO",
                                                         "COD_SIT_CAND_SUPERIOR", 
                                                         "DESC_SIT_CAND_SUPERIOR", 
                                                         "CODIGO_SIT_CANDIDATO", 
                                                         "DESC_SIT_CANDIDATO",
                                                         "CODIGO_SIT_CAND_TOT", 
                                                         "DESC_SIT_CAND_TOT", 
                                                         "NUMERO_PARTIDO", 
                                                         "SIGLA_PARTIDO",
                                                         "NOME_PARTIDO", 
                                                         "SEQUENCIAL_LEGENDA", 
                                                         "NOME_COLIGACAO", 
                                                         "COMPOSICAO_LEGENDA",
                                                         "TOT_VOTOS", 
                                                         "TRANSITO"))

###### PRESTAÇÃO DE CONTAS - RECEITA ###### 
# Nomes das colunas da tabela das prestações de contas de um candidato 

# Em 2006

col_names_receita_2006 <- tolower(c("SQ_CANDIDATO",
                       "NOME_CANDIDATO",
                       "DESCRICAO_CARGO",
                       "CODIGO_CARGO",
                       "NUMERO_CAND",
                       "SIGLA_UF",
                       "CNPJ_CAND",
                       "NUMERO_PARTIDO",
                       "SIGLA_PARTIDO",
                       "VALOR_RECEITA",
                       "DATA_RECEITA",
                       "TIPO_RECEITA",
                       "COD_TIPO_RECEITA",
                       "DESC_TIPO_RECURSO",
                       "COD_TIPO_RECURSO",
                       "NOME_DOADOR",
                       "CPF_CGC_DOADOR",
                       "UF_DOADOR",
                       "ST_CADASTRAL"))

# Em 2010
col_names_receita_2010 <- tolower(c("DATA_E_HORA",
                            "SQ_CANDIDATO",
                            "SIGLA_UF",
                            "SIGLA_PARTIDO",
                            "NUMERO_CAND",
                            "DESCRICAO_CARGO",
                            "NOME_CANDIDATO",
                            "CPF_CAND",
                            "ENTREGA_EM_CONJUNTO",
                            "NUMERO_RECIBO_ELEITORAL",
                            "NUMERO_DOCUMENTO",
                            "CPF_CGC_DOADOR",
                            "NOME_DOADOR",
                            "DATA_RECEITA",
                            "VALOR_RECEITA",
                            "TIPO_RECEITA",
                            "FONTE_RECURSO",
                            "ESPECIE_RECURSO",
                            "DESCRICAO_RECEITA"))

# Em 2014
col_names_receita_2014 <- tolower(c("COD_ELEICAO",
                            "DESC_ELEICAO",
                            "DATA_E_HORA",
                            "CPNJ_CAND",
                            "SQ_CANDIDATO",
                            "SIGLA_UF",
                            "SIGLA_PARTIDO",
                            "NUMERO_CAND",
                            "DESCRICAO_CARGO",
                            "NOME_CANDIDATO",
                            "CPF_CAND",
                            "NUMERO_RECIBO_ELEITORAL",
                            "NUMERO_DOCUMENTO",
                            "CPF_CGC_DOADOR",
                            "NOME_DOADOR",
                            "NOME_DOADOR_RF",
                            "SIGLA_UE_DOADOR",
                            "NUMERO_PARTIDO_DOADOR",
                            "NUMERO_CAND_DOADOR",
                            "COD_SETOR_ECONOMICO_DOADOR",
                            "SETOR_ECONOMICO_DOADOR",
                            "DATA_RECEITA",
                            "VALOR_RECEITA",
                            "TIPO_RECEITA",
                            "FONTE_RECURSO",
                            "ESPECIE_RECURSO",
                            "DESCRICAO_RECEITA",
                            "CPF_CDPNJ_DOADOR_OR",
                            "NOME_DOADOR_OR",
                            "TIPO_DOADOR_OR",
                            "SETOR_ECONOMICO_OR",
                            "NOME_OD_RF"))

###### PRESTAÇÃO DE CONTAS - DESPESAS ###### 
# Nomes das colunas da tabela das prestações de contas de um candidato 

# Em 2006

col_names_despesa_2006 <- tolower(c("SQ_CANDIDATO",
                                    "NOME_CANDIDATO",
                                    "DESCRICAO_CARGO",
                                    "CODIGO_CARGO",
                                    "NUMERO_CAND",
                                    "SIGLA_UF",
                                    "CNPJ_CAND",
                                    "NUMERO_PARTIDO",
                                    "SIGLA_PARTIDO",
                                    "VALOR_DESPESA",
                                    "DATA_DESPESA",
                                    "TIPO_DESPESA",
                                    "COD_TIPO_DESPESA",
                                    "DESC_FORMA_PAGAMENTO",
                                    "COD_FORMA_PAGAMENTO",
                                    "NUMERO_DOCUMENTO",
                                    "TIPO_DOCUMENTO",
                                    "CODIGO_TIPO_DOCUMENTO",
                                    "NOME_FORNECEDOR",
                                    "NUMERO_CPF_CGC_FORNECEDOR",
                                    "UE_FORNECEDOR",
                                    "ST_CADASTRAL"))

# Em 2010
col_names_despesa_2010 <- tolower(c("DATA_E_HORA",
                                    "SQ_CANDIDATO",
                                    "SIGLA_UF",
                                    "SIGLA_PARTIDO",
                                    "NUMERO_CAND",
                                    "DESCRICAO_CARGO",
                                    "NOME_CANDIDATO",
                                    "CPF_CAND",
                                    "ENTREGA_EM_CONJUNTO",
                                    "NUMERO_RECIBO_ELEITORAL",
                                    "NUMERO_DOCUMENTO",
                                    "CPF_CGC_DOADOR",
                                    "NOME_DOADOR",
                                    "DATA_DESPESA",
                                    "VALOR_DESPESA",
                                    "TIPO_DESPESA",
                                    "FONTE_RECURSO",
                                    "ESPECIE_RECURSO",
                                    "DESCRICAO_DESPESA"))

# Em 2014
col_names_despesa_2014 <- tolower(c("COD_ELEICAO",
                                    "DESC_ELEICAO",
                                    "DATA_E_HORA",
                                    "CPNJ_CAND",
                                    "SQ_CANDIDATO",
                                    "SIGLA_UF",
                                    "SIGLA_PARTIDO",
                                    "NUMERO_CAND",
                                    "DESCRICAO_CARGO",
                                    "NOME_CANDIDATO",
                                    "CPF_CAND",
                                    "TIPO_DOCUMENTO",
                                    "NUMERO_DOCUMENTO",
                                    "CPF_CNPJ_FORNECEDOR",
                                    "NOME_FORNECEDOR",
                                    "NOME_FORNECEDOR_RF",
                                    "COD_SETOR_ECONOMICO_FORNECEDOR",
                                    "SETOR_ECONOMICO_FORNECEDOR",
                                    "DATA_DESPESA",
                                    "VALOR_DESPESA",
                                    "TIPO_DESPESA",
                                    "DESCRICAO_DESPESA"))

