# ESTE ARQUIVO TEM COMO FINALIDADE GUARDAR AS CONSTANTES UTILIZADAS PELOS SCRIPTS R.

cargos <- c('DEPUTADO FEDERAL', 'SENADOR')
###### VOTAÇÕES NOMINAIS POR MUNICIPIO E ZONA ###### 
# Nomes das colunas da tabela dos candidatos com munzonas

# Até o ano de 2012
col_names_candidatos_munzona_ate_2012 <- tolower(c("DATA_GERACAO", 
                                                   "HORA_GERACAO",
                                                   "ANO", 
                                                   "NUM_TURNO",
                                                   "DESCRICAO_ELEICAO", 
                                                   "SIGLA_UF", 
                                                   "SIGLA_UE", 
                                                   "CODIGO_MUNICIPIO",
                                                   "NOME_MUNICIPIO", 
                                                   "NUMERO_ZONA", 
                                                   "CODIGO_CARGO", 
                                                   "NUMERO_CAND",
                                                   "SQ_CANDIDATO", 
                                                   "NOME_CANDIDATO", 
                                                   "NOME_URNA_CANDIDATO", 
                                                   "DESCRICAO_CARGO",
                                                   "COD_SIT_CAND_SUPERIOR", 
                                                   "DESC_SIT_CAND_SUPERIOR", 
                                                   "CODIGO_SIT_CANDIDATO", 
                                                   "DESC_SIT_CANDIDATO",
                                                   "CODIGO_SIT_CAND_TOT", 
                                                   "DESC_SIT_CAND_TOT", 
                                                   "NUMERO_PARTIDO", 
                                                   "SIGLA_PARTIDO",
                                                   "NOME_PARTIDO", 
                                                   "SEQUENCIAL_LEGENDA", 
                                                   "NOME_COLIGACAO", 
                                                   "COMPOSICAO_LEGENDA",
                                                   "TOT_VOTOS"))

# A partir do ano de 2014
col_names_candidatos_munzona_2014_em_diante <- tolower(c("DATA_GERACAO", 
                                                         "HORA_GERACAO",
                                                         "ANO", 
                                                         "NUM_TURNO",
                                                         "DESCRICAO_ELEICAO", 
                                                         "SIGLA_UF", 
                                                         "SIGLA_UE", 
                                                         "CODIGO_MUNICIPIO",
                                                         "NOME_MUNICIPIO", 
                                                         "NUMERO_ZONA", 
                                                         "CODIGO_CARGO", 
                                                         "NUMERO_CAND",
                                                         "SQ_CANDIDATO", 
                                                         "NOME_CANDIDATO", 
                                                         "NOME_URNA_CANDIDATO", 
                                                         "DESCRICAO_CARGO",
                                                         "COD_SIT_CAND_SUPERIOR", 
                                                         "DESC_SIT_CAND_SUPERIOR", 
                                                         "CODIGO_SIT_CANDIDATO", 
                                                         "DESC_SIT_CANDIDATO",
                                                         "CODIGO_SIT_CAND_TOT", 
                                                         "DESC_SIT_CAND_TOT", 
                                                         "NUMERO_PARTIDO", 
                                                         "SIGLA_PARTIDO",
                                                         "NOME_PARTIDO", 
                                                         "SEQUENCIAL_LEGENDA", 
                                                         "NOME_COLIGACAO", 
                                                         "COMPOSICAO_LEGENDA",
                                                         "TOT_VOTOS", 
                                                         "TRANSITO"))

# A partir do ano de 2018
col_names_candidatos_munzona_2018 <-           tolower(c("DATA_GERACAO", 
                                                         "HORA_GERACAO",
                                                         "ANO", 
                                                         "CD_TIPO_ELEICAO",
                                                         "NM_TIPO_ELEICAO",
                                                         "NUM_TURNO",
                                                         "CD_ELEICAO",
                                                         "DESCRICAO_ELEICAO",
                                                         "DT_ELEICAO",
                                                         "TP_ABRANGENCIA",
                                                         "SIGLA_UF", 
                                                         "SIGLA_UE", 
                                                         "NM_UE",
                                                         "CODIGO_MUNICIPIO",
                                                         "NOME_MUNICIPIO", 
                                                         "NUMERO_ZONA", 
                                                         "CODIGO_CARGO",
                                                         "DESCRICAO_CARGO",
                                                         "SQ_CANDIDATO", 
                                                         "NUMERO_CAND",
                                                         "NOME_CANDIDATO", 
                                                         "NOME_URNA_CANDIDATO",
                                                         "NOME_SOCIAL_CANDIDATO",
                                                         "COD_SIT_CAND_SUPERIOR", 
                                                         "DESC_SIT_CAND_SUPERIOR", 
                                                         "CODIGO_SIT_CANDIDATO", 
                                                         "DESC_SIT_CANDIDATO",
                                                         "TP_AGREMIACAO",
                                                         "NUMERO_PARTIDO", 
                                                         "SIGLA_PARTIDO",
                                                         "NOME_PARTIDO", 
                                                         "SEQUENCIAL_LEGENDA", 
                                                         "NOME_COLIGACAO", 
                                                         "COMPOSICAO_LEGENDA",
                                                         "CODIGO_SIT_CAND_TOT", 
                                                         "DESC_SIT_CAND_TOT", 
                                                         "TRANSITO",
                                                         "TOT_VOTOS"
                                                         ))

###### PRESTAÇÃO DE CONTAS - RECEITA ###### 
# Nomes das colunas da tabela das prestações de contas de um candidato 

# Em 2006

col_names_receita_2006 <- tolower(c("SQ_CANDIDATO",
                                    "NOME_CANDIDATO",
                                    "DESCRICAO_CARGO",
                                    "CODIGO_CARGO",
                                    "NUMERO_CAND",
                                    "SIGLA_UF",
                                    "CNPJ_CAND",
                                    "NUMERO_PARTIDO",
                                    "SIGLA_PARTIDO",
                                    "VALOR_RECEITA",
                                    "DATA_RECEITA",
                                    "TIPO_RECEITA",
                                    "COD_TIPO_RECEITA",
                                    "DESC_TIPO_RECURSO",
                                    "COD_TIPO_RECURSO",
                                    "NOME_DOADOR",
                                    "CPF_CGC_DOADOR",
                                    "UF_DOADOR",
                                    "ST_CADASTRAL"))

# Em 2010
col_names_receita_2010 <- tolower(c("DATA_E_HORA",
                                    "SQ_CANDIDATO",
                                    "SIGLA_UF",
                                    "SIGLA_PARTIDO",
                                    "NUMERO_CAND",
                                    "DESCRICAO_CARGO",
                                    "NOME_CANDIDATO",
                                    "CPF_CAND",
                                    "ENTREGA_EM_CONJUNTO",
                                    "NUMERO_RECIBO_ELEITORAL",
                                    "NUMERO_DOCUMENTO",
                                    "CPF_CGC_DOADOR",
                                    "NOME_DOADOR",
                                    "DATA_RECEITA",
                                    "VALOR_RECEITA",
                                    "TIPO_RECEITA",
                                    "FONTE_RECURSO",
                                    "ESPECIE_RECURSO",
                                    "DESCRICAO_RECEITA"))

# Em 2014
col_names_receita_2014 <- tolower(c("COD_ELEICAO",
                                    "DESC_ELEICAO",
                                    "DATA_E_HORA",
                                    "CPNJ_CAND",
                                    "SQ_CANDIDATO",
                                    "SIGLA_UF",
                                    "SIGLA_PARTIDO",
                                    "NUMERO_CAND",
                                    "DESCRICAO_CARGO",
                                    "NOME_CANDIDATO",
                                    "CPF_CAND",
                                    "NUMERO_RECIBO_ELEITORAL",
                                    "NUMERO_DOCUMENTO",
                                    "CPF_CGC_DOADOR",
                                    "NOME_DOADOR",
                                    "NOME_DOADOR_RF",
                                    "SIGLA_UE_DOADOR",
                                    "NUMERO_PARTIDO_DOADOR",
                                    "NUMERO_CAND_DOADOR",
                                    "COD_SETOR_ECONOMICO_DOADOR",
                                    "SETOR_ECONOMICO_DOADOR",
                                    "DATA_RECEITA",
                                    "VALOR_RECEITA",
                                    "TIPO_RECEITA",
                                    "FONTE_RECURSO",
                                    "ESPECIE_RECURSO",
                                    "DESCRICAO_RECEITA",
                                    "CPF_CDPNJ_DOADOR_OR",
                                    "NOME_DOADOR_OR",
                                    "TIPO_DOADOR_OR",
                                    "SETOR_ECONOMICO_OR",
                                    "NOME_OD_RF"))

###### PRESTAÇÃO DE CONTAS - DESPESAS ###### 
# Nomes das colunas da tabela das prestações de contas de um candidato 

# Em 2006

col_names_despesa_2006 <- tolower(c("SQ_CANDIDATO",
                                    "NOME_CANDIDATO",
                                    "DESCRICAO_CARGO",
                                    "CODIGO_CARGO",
                                    "NUMERO_CAND",
                                    "SIGLA_UF",
                                    "CNPJ_CAND",
                                    "NUMERO_PARTIDO",
                                    "SIGLA_PARTIDO",
                                    "VALOR_DESPESA",
                                    "DATA_DESPESA",
                                    "TIPO_DESPESA",
                                    "COD_TIPO_DESPESA",
                                    "DESC_FORMA_PAGAMENTO",
                                    "COD_FORMA_PAGAMENTO",
                                    "NUMERO_DOCUMENTO",
                                    "TIPO_DOCUMENTO",
                                    "CODIGO_TIPO_DOCUMENTO",
                                    "NOME_FORNECEDOR",
                                    "NUMERO_CPF_CGC_FORNECEDOR",
                                    "UE_FORNECEDOR",
                                    "ST_CADASTRAL"))

# Em 2010
col_names_despesa_2010 <- tolower(c("DATA_E_HORA",
                                    "SQ_CANDIDATO",
                                    "SIGLA_UF",
                                    "SIGLA_PARTIDO",
                                    "NUMERO_CAND",
                                    "DESCRICAO_CARGO",
                                    "NOME_CANDIDATO",
                                    "CPF_CAND",
                                    "ENTREGA_EM_CONJUNTO",
                                    "NUMERO_RECIBO_ELEITORAL",
                                    "NUMERO_DOCUMENTO",
                                    "CPF_CGC_DOADOR",
                                    "NOME_FORNECEDOR",
                                    "DATA_DESPESA",
                                    "VALOR_DESPESA",
                                    "TIPO_DESPESA",
                                    "FONTE_RECURSO",
                                    "ESPECIE_RECURSO",
                                    "DESCRICAO_DESPESA"))

# Em 2014
col_names_despesa_2014 <- tolower(c("COD_ELEICAO",
                                    "DESC_ELEICAO",
                                    "DATA_E_HORA",
                                    "CPNJ_CAND",
                                    "SQ_CANDIDATO",
                                    "SIGLA_UF",
                                    "SIGLA_PARTIDO",
                                    "NUMERO_CAND",
                                    "DESCRICAO_CARGO",
                                    "NOME_CANDIDATO",
                                    "CPF_CAND",
                                    "TIPO_DOCUMENTO",
                                    "NUMERO_DOCUMENTO",
                                    "CPF_CNPJ_FORNECEDOR",
                                    "NOME_FORNECEDOR",
                                    "NOME_FORNECEDOR_RF",
                                    "COD_SETOR_ECONOMICO_FORNECEDOR",
                                    "SETOR_ECONOMICO_FORNECEDOR",
                                    "DATA_DESPESA",
                                    "VALOR_DESPESA",
                                    "TIPO_DESPESA",
                                    "DESCRICAO_DESPESA"))

###### CANDIDATOS ###### 
# Nomes das colunas da tabela dos candidatos

# Até o ano de 2010
col_names_candidatos_ate_2010 <- tolower(c(
  "DATA_GERACAO", 
  "HORA_GERACAO", 
  "ANO",
  "NUM_TURNO", 
  "DESCRICAO_ELEICAO", 
  "SIGLA_UF",
  "COD_CIDADE", 
  "NOME_MUNICIPIO", 
  "COD_CARGO", 
  "DESCRICAO_CARGO", 
  "NOME_CANDIDATO",
  "SQ_CANDIDATO", 
  "NUMERO_CAND",
  "CPF_CANDIDATO", 
  "NOME_URNA_CANDIDATO",
  "COD_SIT_CANDIDATURA", 
  "DESC_SIT_CANDIDATO", 
  "NUMERO_PARTIDO", 
  "SIGLA_PARTIDO",
  "NOME_PARTIDO", 
  "CODIGO_LEGENDA",
  "SIGLA_LEGENDA",
  "COMPOSICAO_LEGENDA", 
  "NOME_COLIGACAO", 
  "CODIGO_OCUPACAO",
  "DESCRICAO_OCUPACAO", 
  "DATA_NASCIMENTO", 
  "NUM_TIT_ELEITORAL_CANDIDATO",
  "IDADE_DATA_CANDIDATO", 
  "COD_SEXO", 
  "SEXO", 
  "COD_GRAU_INSTRUCAO",
  "GRAU_INSTRUCAO", 
  "COD_ESTADO_CIVIL", 
  "ESTADO_CIVIL",
  "CODIGO_NACIONALIDADE",
  "DESCRICAO_NACIONALIDADE", 
  "SIGLA_UF_NASCIMENTO",
  "COD_MUNICIPIO_NASCIMENTO", 
  "NOME_MUNICIPIO_NASCIMENTO",
  "DESPESA_MAX_CAMPANHA", 
  "COD_SIT_TOT_TURNO",
  "DESC_SIT_CAND_TOT"))

# No ano de 2012
col_names_candidatos_2012 <- tolower(c("DATA_GERACAO", 
                                       "HORA_GERACAO", 
                                       "ANO",
                                       "NUM_TURNO", 
                                       "DESCRICAO_ELEICAO", 
                                       "SIGLA_UF",
                                       "COD_CIDADE", 
                                       "NOME_MUNICIPIO", 
                                       "COD_CARGO", 
                                       "DESCRICAO_CARGO", 
                                       "NOME_CANDIDATO",
                                       "SQ_CANDIDATO", 
                                       "NUMERO_CAND",
                                       "CPF_CANDIDATO", 
                                       "NOME_URNA_CANDIDATO",
                                       "COD_SIT_CANDIDATURA", 
                                       "DESC_SIT_CANDIDATO", 
                                       "NUMERO_PARTIDO", 
                                       "SIGLA_PARTIDO",
                                       "NOME_PARTIDO", 
                                       "CODIGO_LEGENDA",
                                       "SIGLA_LEGENDA",
                                       "COMPOSICAO_LEGENDA", 
                                       "NOME_COLIGACAO", 
                                       "CODIGO_OCUPACAO",
                                       "DESCRICAO_OCUPACAO", 
                                       "DATA_NASCIMENTO", 
                                       "NUM_TIT_ELEITORAL_CANDIDATO",
                                       "IDADE_DATA_CANDIDATO", 
                                       "COD_SEXO", 
                                       "SEXO", 
                                       "COD_GRAU_INSTRUCAO",
                                       "GRAU_INSTRUCAO", 
                                       "COD_ESTADO_CIVIL", 
                                       "ESTADO_CIVIL",
                                       "CODIGO_NACIONALIDADE",
                                       "DESCRICAO_NACIONALIDADE", 
                                       "SIGLA_UF_NASCIMENTO",
                                       "COD_MUNICIPIO_NASCIMENTO", 
                                       "NOME_MUNICIPIO_NASCIMENTO",
                                       "DESPESA_MAX_CAMPANHA", 
                                       "COD_SIT_TOT_TURNO",
                                       "DESC_SIT_CAND_TOT", 
                                       "EMAIL"))

# A partir de 2014
col_names_candidatos_2014_em_diante <- tolower(c("DATA_GERACAO", 
                                                 "HORA_GERACAO", 
                                                 "ANO",
                                                 "NUM_TURNO", 
                                                 "DESCRICAO_ELEICAO", 
                                                 "SIGLA_UF",
                                                 "COD_CIDADE", 
                                                 "NOME_MUNICIPIO", 
                                                 "COD_CARGO", 
                                                 "DESCRICAO_CARGO", 
                                                 "NOME_CANDIDATO",
                                                 "SQ_CANDIDATO", 
                                                 "NUMERO_CAND",
                                                 "CPF_CANDIDATO", 
                                                 "NOME_URNA_CANDIDATO",
                                                 "COD_SIT_CANDIDATURA", 
                                                 "DESC_SIT_CANDIDATO", 
                                                 "NUMERO_PARTIDO", 
                                                 "SIGLA_PARTIDO",
                                                 "NOME_PARTIDO", 
                                                 "CODIGO_LEGENDA",
                                                 "SIGLA_LEGENDA",
                                                 "COMPOSICAO_LEGENDA", 
                                                 "NOME_COLIGACAO", 
                                                 "CODIGO_OCUPACAO",
                                                 "DESCRICAO_OCUPACAO", 
                                                 "DATA_NASCIMENTO", 
                                                 "NUM_TIT_ELEITORAL_CANDIDATO",
                                                 "IDADE_DATA_CANDIDATO", 
                                                 "COD_SEXO", 
                                                 "SEXO", 
                                                 "COD_GRAU_INSTRUCAO",
                                                 "GRAU_INSTRUCAO", 
                                                 "COD_ESTADO_CIVIL", 
                                                 "ESTADO_CIVIL",
                                                 "COD_COR_RACA", 
                                                 "COR_RACA", 
                                                 "CODIGO_NACIONALIDADE",
                                                 "DESCRICAO_NACIONALIDADE", 
                                                 "SIGLA_UF_NASCIMENTO",
                                                 "COD_MUNICIPIO_NASCIMENTO", 
                                                 "NOME_MUNICIPIO_NASCIMENTO",
                                                 "DESPESA_MAX_CAMPANHA", 
                                                 "COD_SIT_TOT_TURNO",
                                                 "DESC_SIT_CAND_TOT", 
                                                 "EMAIL"))

# Em 2018
col_names_candidatos_2018 <-           tolower(c("DATA_GERACAO", 
                                                 "HORA_GERACAO", 
                                                 "ANO",
                                                 "CD_TIPO_ELEICAO",
                                                 "NM_TIPO_ELEICAO",
                                                 "NUM_TURNO", 
                                                 "CD_ELEICAO",
                                                 "DESCRICAO_ELEICAO",
                                                 "DATA_ELEICAO",
                                                 "TP_ABRANGENCIA",
                                                 "SIGLA_UF",
                                                 "COD_CIDADE", 
                                                 "NOME_MUNICIPIO", 
                                                 "COD_CARGO", 
                                                 "DESCRICAO_CARGO", 
                                                 "SQ_CANDIDATO",
                                                 "NUMERO_CAND",
                                                 "NOME_CANDIDATO",
                                                 "NOME_URNA_CANDIDATO",
                                                 "NOME_SOCIAL_CANDIDATO",
                                                 "CPF_CANDIDATO", 
                                                 "EMAIL",
                                                 "COD_SIT_CANDIDATURA", 
                                                 "DESC_SIT_CANDIDATO",
                                                 "CD_DETALHE_SIT_CAND",
                                                 "DS_DETALHE_SIT_CAND",
                                                 "TP_AGREMIACAO",
                                                 "NUMERO_PARTIDO", 
                                                 "SIGLA_PARTIDO",
                                                 "NOME_PARTIDO", 
                                                 "CODIGO_LEGENDA",
                                                 "SIGLA_LEGENDA",
                                                 "COMPOSICAO_LEGENDA", 
                                                 "CODIGO_NACIONALIDADE",
                                                 "DESCRICAO_NACIONALIDADE", 
                                                 "SG_UF_NASCIMENTO", 
                                                 "CD_MUN_NASCIMENTO",
                                                 "NM_MUN_NASCIMENTO",
                                                 "DATA_NASCIMENTO",
                                                 "NR_IDADE_DATA_POSSE",
                                                 "NUM_TIT_ELEITORAL_CANDIDATO",
                                                 "COD_SEXO", 
                                                 "SEXO", 
                                                 "COD_GRAU_INSTRUCAO",
                                                 "GRAU_INSTRUCAO", 
                                                 "COD_ESTADO_CIVIL", 
                                                 "ESTADO_CIVIL",
                                                 "COD_COR_RACA", 
                                                 "COR_RACA",
                                                 "CODIGO_OCUPACAO",
                                                 "DESCRICAO_OCUPACAO", 
                                                 "DESPESA_MAX_CAMPANHA", 
                                                 "COD_SIT_TOT_TURNO",
                                                 "DESC_SIT_CAND_TOT", 
                                                 "ST_REELEICAO",
                                                 "ST_DECLARAR_BENS",
                                                 "NR_PROTOCOLO_CAND",
                                                 "NR_PROCESSO"))

## COLUNAS DO DATAFRAME FINAL
col_names_dataframe <- tolower(c(
  "ANO",
  "SEQUENCIAL_CANDIDATO",
  "NOME",
  "UF",
  "PARTIDO",
  "QUANTIDADE_DOACOES",
  "QUANTIDADE_DOADORES",
  "TOTAL_RECEITA",
  "MEDIA_RECEITA",
  "RECURSOS_DE_OUTROS_CANDIDATOS.COMITES",
  "RECURSOS_DE_PESSOAS_FISICAS",
  "RECURSOS_DE_PESSOAS_JURIDICAS",
  "RECURSOS_PROPRIOS",
  "RECURSOS_DE_PARTIDO_POLITICO",
  "QUANTIDADE_DESPESAS",
  "QUANTIDADE_FORNECEDORES",
  "TOTAL_DESPESA",
  "MEDIA_DESPESA",
  "CARGO",
  "SEXO",
  "GRAU",
  "ESTADO_CIVIL",
  "OCUPACAO",
  "VOTOS"))

